In [9]:
### Perceptron Algorithm without offset
import numpy as np
# start from 1
# X = [[-1, -1], [1,0], [-1, 1.5]]
X = [[-1,0,0], [0,1,0], [0, 0, -1]]


# start from 2
# X = [[1,0], [-1, 1.5], [-1, -1]]
# X = [[1,0], [-1, 10], [-1, -1]]

X = np.array(X)

# start from 1
y = [1, 1, 1]

# start from 2
# y = [-1, 1, 1]

y=np.array(y)

theta = np.array([0, 0, 0])
theta_0 = 0
for i in range(10):
    error_counter = 0
    for j in range(len(X)):
        if y[j]*np.dot(X[j], theta) <= 0:
            theta = theta + y[j]*X[j]
            print("Error in ", j)
            print(theta)
            error_counter += 1
    if error_counter == 0:
        break

print(f"number of interation to convergence: {i}")


Error in  0
[-1  0  0]
Error in  1
[-1  1  0]
Error in  2
[-1  1 -1]
number of interation to convergence: 1


In [1]:
### Perceptron Algorithm with offset
import numpy as np
# start from 1
X = [[-1,1], [1,-1], [1,1], [2,2]]

# start from 2
# X = [[1,0], [-1, 1.5], [-1, -1]]
# X = [[1,0], [-1, 10], [-1, -1]]

X = np.array(X)

# start from 1
y = [1, 1, -1, -1]

# start from 2
# y = [-1, 1, 1]

y=np.array(y)

theta = [-3, 3]
theta_0 = -3
for i in range(10):
    error_counter = 0
    for j in range(len(X)):
        if y[j]*(np.dot(X[j], theta) + theta_0) <= 0:
            theta = theta + y[j]*X[j]
            theta_0 += y[j]
            print("Error in ", j)
            print(theta)
            print(theta_0)
            error_counter += 1
    if error_counter == 0:
        break

print(f"number of interation to convergence: {i}")

Error in  1
[-2  2]
-2
Error in  1
[-1  1]
-1
Error in  1
[0 0]
0
Error in  2
[-1 -1]
-1
Error in  0
[-2  0]
0
Error in  1
[-1 -1]
1
number of interation to convergence: 4
